### ISSUE TITLE
Load-out Editor Maxed out at 7 of 8 Machinegun Mounts

### ISSUE THREAD

**Issue by TheLeviathan** [HerbertV/Aeronaut#14]
Load-out Editor:  only 7 of 8 machinegun mounts show up with associated ammo selection pull-down menus for those aircraft that have 8 machineguns

**Comment by HerbertV** [comment]
Thank for posting. I will look into it, as soon as possible.

**Comment by TheLeviathan** [comment]
You are welcome!  I am so impressed by your work with Aeronaut and appreciate all of your efforts to share Crimson Skies with the rest of us.  Thanks so much.  I cannot wait for the coming Bombers and Zeppelins versions!
 Date: Mon, 10 Dec 2012 10:25:36 -0800

**Comment by TheLeviathan** [comment]
HebertV, you rule.  Thanks for this great product!

**Comment by HerbertV** [comment]
No problem, thanks for your report. I will upload the compiled  version this evening. ;)
