### ISSUE TITLE
New Components count towards Special Characteristics limit

### ISSUE THREAD

**Issue by GSS-Bandit** [HerbertV/Aeronaut#2]
"New Components" (like "Nitro Injectors" or "Brake Chutes") are falsely counted as "Special Characteristics". The amount of the latter is limited by the base to-hit number of the craft, whereas "New Components" should only be limited by weight.

**Comment by HerbertV** [comment]
Ok so I will need to add some kind of flag (eg. counts to limit)

**Comment by HerbertV** [comment]
The flag is now available. I just need to change the limit implementation inside CSWindowAircraft this should also fix issue #1
